<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository {

    public function getAdverts($page, $nbPerPage) {
        $query = $this->createQueryBuilder("a")
                ->leftJoin("a.image", "i")
                ->addSelect("i")
                ->leftJoin("a.categories", "c")
                ->addSelect("c")
                ->orderBy("a.date", "DESC")
                ->getQuery();

        $query->setFirstResult(($page - 1) * $nbPerPage)
                ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }

    public function findByAuthorAndDate($author, $date) {
        $qb = $this->createQueryBuilder('a');

        $qb->where("a.author = :author")
                ->setParameter("author", $author)
                ->andWhere("a.date < :date")
                ->setParameter("date", $date)
                ->orderBy("a.date", "DESC");
        return $qb->getQuery()->getResult();
    }

    public function getAdvertWithApplications() {
        $qb = $this->createQueryBuilder("a")
                ->leftJoin("a.applications", "app")
                ->addSelect("app");

        return $qb->getQuery()->getResult();
    }

    public function getAdvertWithCategory(array $categoryNames) {
        $qb = $this->createQueryBuilder("a")
                ->innerJoin("a.categories", "category")
                ->addSelect("category")
                ->where($qb->expr()->in("category.name", "(:categories)"))
                ->setParameter("categories", $categoryNames);

        $qb->getQuery()->getResult();
    }

}
